--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/mcsim415/Parkour
build-by-default: true
branches:
- main
projects:
  Parkour:
    lint:
      phpstan: false
    path: ""
    icon: "parkour.png"
...
