name: Build Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make '.build' directory
        run: mkdir .build

      - name: Download DevTools/ConsoleScript.php
        run: wget -O .build/build.php https://raw.githubusercontent.com/pmmp/DevTools/master/src/ConsoleScript.php

      - name: Build source to artifact.phar
        run: php -dphar.readonly=0 .build/build.php --make ./ --out .build/WParkour.phar

      - name: Display structure of current working directory
        run: ls -R

      - name: Upload WParkour.phar to releases
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'WParkour'
          files: |
            .build/WParkour.phar
